title = '전자음악 갤러리 2021년 연말결산'
description = '디시인사이드 전자음악 갤러리 이용자들이 선정한 2021년 결산 결과'
base_url = "https://eleclambda.github.io/2021aoty"
default_language = 'ko'

compile_sass = true
minify_html = true

generate_feed = false
build_search_index = false

ignored_content = ['*.csv']

[markdown]
highlight_code = false
smart_punctuation = true
render_emoji = false

[extra]
author = 'λ'
github = 'eleclambda'
google_analytics = 'UA-104952551-2'
